Bug fixes for GUI and Websocket connections
NOAA-OWP/DMOD pull request #131
Opened 2022-01-31 18:14 UTC by robertbartel

- Fix typo in `nwm_gui` Docker stack `app_server` service volume config
- Fix bug with WebSocketInterface related to extending MaaSRequest class to ModelExecRequest 
- Bumping Python package deps and versions
- Updating version of `dmod.communication` package required by GUI code

2022-01-31 19:27 UTC, mattw-nws commented
Am I missing it or are all the dependency bumps OWP software? No external dependencies actually changed?

2022-02-01 14:15 UTC, robertbartel commented
This PR probably needs to be merged prior to final review of #130.

2022-02-01 14:18 UTC, robertbartel commented
@mattw-nws, correct.  These are internal dependency relationships between the different namespace packages.  There is just a bit of a domino effect.

As a brief aside: the package architecture probably needs to be revisited to avoid the dependency complexity we are seeing right now, but that will have to be addressed later.

2022-02-07 14:00 UTC, mattw-nws requested changes

2022-02-07 14:00 UTC, mattw-nws commented on python/services/requestservice/setup.py
> +    install_requires=['websockets', 'dmod-communication>=0.4.2', 'dmod-access>=0.2.0',
Notably [/python/lib/access/dmod/access/_version.py](https://github.com/robertbartel/DMOD/blob/stack_fixes/websockservice/python/lib/access/dmod/access/_version.py) still shows `0.1.1`, so is this an error or are there missing changes in dmod-access, perhaps?

2022-02-09 17:10 UTC, mattw-nws approved these changes

2022-02-09 17:11 UTC, merged