Json editor for eval admin
NOAA-OWP/DMOD pull request #406
Opened 2023-07-28 13:15 UTC by christophertubbs

Created the functionality used to view and edit json data in several views on the evaluation service admin site

closes #390

2023-08-04 19:35 UTC, aaraney requested changes
A few minor changes and we should be good to go! Thanks, @christophertubbs!

2023-08-04 20:29 UTC, christophertubbs commented on python/lib/evaluations/dmod/test/specification/test_deserialization.py
> +        pprint(dir(specification.EvaluationSpecification))
... you weren't supposed to see that. Removed.

2023-08-04 20:32 UTC, christophertubbs commented on python/services/evaluationservice/dmod/evaluationservice/evaluation_service/forms/json.py
> +A regular expression that finds all type definitions that are strings formatted as bytes
Just added a details explanation on what strings will be found with the regex, what the regex is used for, and why the two extremely similar forms are necessary.

2023-08-07 12:39 UTC, aaraney approved these changes
Thanks for working through this with me, @christophertubbs!

2023-08-07 12:40 UTC, merged