Evaluation Service REST conversion
NOAA-OWP/DMOD pull request #435
Opened 2023-09-20 18:38 UTC by christophertubbs

Created copies of CRUD calls that _were_ going through websockets that instead go through GET and POST requests.

This includes formal messages and new views.

Prototypes for the next.js interface are along for the ride.

2023-09-29 17:46 UTC, aaraney requested changes
I left a few minor comments that should be pretty easy to get through. Thanks, @christophertubbs!

2023-09-29 17:46 UTC, aaraney commented on python/services/evaluationservice/dmod/evaluationservice/utilities/common.py
> +    return {"HTTP_AUTHORIZATION": f"Basic {base64.b64encode(username_and_password).decode()}"}
It might be worth adding a comment here noting that this is a django specific keyword argument that gets turned into an `Authorization` header.

2023-09-29 18:47 UTC, christophertubbs commented on python/lib/core/dmod/core/common/__init__.py
> +    def default(cls) -> Status:
This is fine here due to the inclusion of `from __future__ import annotations` at the top of the file.

2023-09-29 18:50 UTC, christophertubbs commented on python/lib/core/dmod/core/common/types.py
> +    def __init__(self, text: str, value: _T, *, group: str = None, index: int = None):
`group: str = None` is interpreted as `typing.Optional[str]` implicitly due to that `= None`. I _think_ the parameter list in a signature like this is the only place where that works.

2023-10-10 13:54 UTC, aaraney commented on python/lib/core/dmod/core/common/__init__.py
> +    def default(cls) -> Status:
Noice, I must have missed that import.

2023-10-10 14:11 UTC, aaraney approved these changes
This looks good to me! Thanks for working through this with me, @christophertubbs!

2024-01-25 16:08 UTC, robertbartel commented
@christophertubbs, is this just waiting on resolving the conflicts with recent changes?

2024-01-25 16:24 UTC, christophertubbs commented
THIS HASN'T BEEN MERGED?!

Oof, yeah, it needs resolved. Let me jump through all that. This needs to be in there asap.

2024-01-25 16:57 UTC, robertbartel commented
Didn't we just deal with something else causing failures like this in another issue?  Any chance the rebase didn't quite get everything in the latest master?

2024-01-25 19:19 UTC, christophertubbs commented
Fixed. Someone please review and merge it before it becomes out of date again.

2024-01-25 19:34 UTC, aaraney approved these changes

2024-01-25 19:34 UTC, merged